### ISSUE TITLE
MonacoProviderService.colorizeElement error with Monaco Editor 0.17.0

### ISSUE THREAD

**Issue by mecsco** [alauda/ng-monaco-editor#13]
After upgrading to Monaco Editor 0.17.0, an error occurs when building

`ERROR in node_modules/ng-monaco-editor/monaco-provider.service.d.ts(42,138): error TS2694: Namespace '"<dir>/node_modules/monaco-editor/esm/vs/editor/editor.api"' has
no exported member 'Promise'.`

This is within MonacoProviderService for the return value of the colorizeElement function (`import("monaco-editor").Promise<void>`)

The changelog at https://github.com/microsoft/monaco-editor/blob/master/CHANGELOG.md mentions (in 0.16.0) a breaking change that sounds related: 

> We are no longer shipping WinJS.Promise, but we are shipping with a Promise shim (for IE11)

**Comment by pengx17** [comment]
I will fix this by the end of this week. Thanks :)
