### ISSUE TITLE
ERROR in node_modules/ng-monaco-editor/resize-sensor.service.d.ts(1,30): error TS2307: Cannot find module 'css-element-queries'.

### ISSUE THREAD

**Issue by jesusvallez** [alauda/ng-monaco-editor#4]

**Comment by pengx17** [comment]
This lib is dependent on `css-element-queries` for resizing the editor. You may already saw it when you do npm install.

Other peer dependencies:
```
    "css-element-queries": "^1.0.2",
    "lodash": "^4.17.11",
    "lodash.debounce": "^4.0.8",
    "lodash.isequal": "^4.5.0",
    "monaco-editor": "^0.15.2",
    "zone.js": "^0.8.26"
```

**Comment by Nexxado** [comment]
Why is it a peer-dependency and not a direct dependency?
as a peer-dependency it means i have to maintain the correct version in my project instead of it coming together with this library.

**Comment by Nexxado** [comment]
Why is it a peer-dependency and not a regular dependency?
As a peer-dependency it means i have to maintain the correct version of it in my project instead of it coming with the library.

**Npm install output:**
```
npm WARN ng-monaco-editor@1.0.8 requires a peer of css-element-queries@^1.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ng-monaco-editor@1.0.8 requires a peer of lodash@^4.17.11 but none is installed. You must install peer dependencies yourself.
npm WARN ng-monaco-editor@1.0.8 requires a peer of lodash.isequal@^4.5.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by Nexxado** [comment]
@pengx17 I'm sorry if I came off negatively towards you, it was not my intention.

Thanks for your time and work, I really do appreciate it.
