### ISSUE TITLE
Typescript compile error (duplicate import?)

### ISSUE THREAD

**Issue by fridolin-koch** [alauda/ng-monaco-editor#44]
Hello,

I've tried to import the component using the ESM method proposed in the readme.

```typescript
    MonacoEditorModule.forRoot({
      dynamicImport: () => import('monaco-editor/esm/vs/editor/editor.api'),
    }),
```

When angular compiles the app I get the following error.

```
Error: node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts:12:9 - error TS2451: Cannot redeclare block-scoped variable 'MonacoEnvironment'.

12     let MonacoEnvironment: Environment | undefined;
           ~~~~~~~~~~~~~~~~~

  node_modules/monaco-editor/monaco.d.ts:11:13
    11 declare let MonacoEnvironment: monaco.Environment | undefined;
                   ~~~~~~~~~~~~~~~~~
    'MonacoEnvironment' was also declared here.


Error: node_modules/monaco-editor/monaco.d.ts:11:13 - error TS2451: Cannot redeclare block-scoped variable 'MonacoEnvironment'.

11 declare let MonacoEnvironment: monaco.Environment | undefined;
               ~~~~~~~~~~~~~~~~~

  node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts:12:9
    12     let MonacoEnvironment: Environment | undefined;
               ~~~~~~~~~~~~~~~~~
    'MonacoEnvironment' was also declared here.
```

I'm not so sure whats happening, as I don't have any meaningful experience with monaco editor. I suspect the API definitions are imported multiple times? The only reference to monaco I could found inside this repo is here https://github.com/alauda/ng-monaco-editor/blob/master/src/public-api.ts#L1

I'm using the following versions:

```json
    "monaco-editor": "^0.22.3",
    "ng-monaco-editor": "^3.0.0",
```

Any Ideas whats going on here?

Thank you very much!

Best Regards,
Frido

**Comment by JounQin** [comment]
Hi, thanks for reporting. Can you provide a minimal reproduction?

**Comment by fridolin-koch** [comment]
Sure: https://github.com/fridolin-koch/bug-ng-monaco-editor-44

Just perform `yarn install && ng serve`

**Comment by fridolin-koch** [comment]
Downgrading monaco to 0.19.x seems to resolve the issue

**Comment by JounQin** [comment]
Closed for now, if you think it's a bug of this module, provide a reproduce and tell me again.
